name: CI Pipeline
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Simple Test
        run: |
          echo "Proje dosyaları:"
          ls -la
          echo "Python sürümü:"
          python --version